<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5bf2aa8d477d8',
        'title' => 'Raatilais-sidebar',
        'fields' => array(
            array(
                'key' => 'field_5bf2aa9d9cfd4',
                'label' => 'Raatilainen',
                'name' => 'fk_raatilainen',
                'type' => 'post_object',
                'instructions' => 'Se raativirka, joka halutaan näytettävän sivun yhteydessä',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'raatilaiset',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
            array(
                'key' => 'field_5bf2aa9d9cfd5',
                'label' => 'Toinen raatilainen',
                'name' => 'fk_raatilainen2',
                'type' => 'post_object',
                'instructions' => 'Se toinen raativirka, joka halutaan näytettävän sivun yhteydessä',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'raatilaiset',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'raatilaiset',
                ),
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-raatiside.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => 'Mahdollista näytettävän raatilaisen valinta sivupohjissa.',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5bf2785510f61',
        'title' => 'Raatilais-CVP',
        'fields' => array(
            array(
                'key' => 'field_5bf2b86dba290',
                'label' => 'Virka',
                'name' => 'raati_virka',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf2787ef1543',
                'label' => 'Nimi',
                'name' => 'raati_nimi',
                'type' => 'text',
                'instructions' => 'Raatilaisen koko nimi',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf27a3cf1547',
                'label' => 'Vuosikurssi',
                'name' => 'raati_vk',
                'type' => 'text',
                'instructions' => 'Vuosikurssi, esim: (TFM V)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf278e4f1544',
                'label' => 'Maili',
                'name' => 'raati_mail',
                'type' => 'email',
                'instructions' => 'Raatilaisen sähköpostiosoite',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5bf27956f1545',
                'label' => 'Puhelin',
                'name' => 'raati_puhelin',
                'type' => 'text',
                'instructions' => 'Raatilaisen puhelinnumero',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c74ebff3f231',
                'label' => 'Telegram',
                'name' => 'raati_tg',
                'type' => 'text',
                'instructions' => 'Raatilaisen TG-nick, e.g. @puheenjohtaja',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5bf279a6f1546',
                'label' => 'Kuva',
                'name' => 'raati_kuva',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5c692bb2a37b4',
                'label' => 'Onko raativirka',
                'name' => 'raati_yesno',
                'type' => 'true_false',
                'instructions' => 'Valitse, jos virka on raativirka (älä, jos virka on toimihenkilövirka).',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'raatilaiset',
                ),
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
            1 => 'excerpt',
            2 => 'discussion',
            3 => 'comments',
            4 => 'page_attributes',
            5 => 'featured_image',
            6 => 'categories',
            7 => 'tags',
            8 => 'send-trackbacks',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;
